name: Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Bazel Setup
        uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: "Coverage"
        run: bazel test //... && bazel coverage --combined_report=lcov //... && third-party/lcov/bin/genhtml bazel-testlogs/pkg/proto/proto_test/coverage.dat -o ./target/coverage -t "Proto Diagram Tool"

      - name: "Coverage Badge"
        uses: rrmcguinness/lcov_gh_badges@e3e6fdc2cbc6e7e8f4f7dcfed0ff365d3f128d4c
        with:
          file: ./bazel-testlogs/pkg/proto/proto_test/coverage.dat
          access_token: ${{ secrets.COVERAGE_SECRET }}

