name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Bazel Setup
        uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: "Test"
        run: bazel test //...

      - name: "Coverage"
        run: bazel coverage --combined_report=lcov //...

      - name: "Coverage Report"
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./bazel-testlogs/pkg/proto/proto_test/coverage.dat

      - name: "Build"
        run: bazel build //...
