name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Bazel Setup
        uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: "Test"
        run: bazel test //...

      - name: "Build"
        run: bazel build //...

      - name: "Compute Coverage"
        uses: rrmcguinness/lcov_gh_badges@c67716e1eda277d60a6a75d7b9f1717bc4b67ab3
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          dat_file: ./bazel-testlogs/pkg/proto/proto_test/coverage.dat
          gist_id: e2d1696c1ef0cbc67ef8bcbbfc46313a
