name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Bazel Setup
        uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: "Test"
        run: bazel test //...

      - name: "Coverage"
        run: bazel coverage --combined_report=lcov //...

      - name: "Coverage Report"
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: ./bazel-testlogs/pkg/proto/proto_test/coverage.dat
          minimum-coverage: 70
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./

      - name: "Build"
        run: bazel build //...
