name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Bazel Setup
        uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: "Test"
        run: bazel test //... && bazel coverage //...

      - name: "Build"
        run: bazel build //...

      - name: "Coverage Badge"
        uses: rrmcguinness/lcov_gh_badges@3d302bf663e45a63f58a7dd8231042bf3b9bf6e0
        with:
          file: ./bazel-testlogs/pkg/proto/proto_test/coverage.dat
